nombre: name
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Kahoot Angular
        uses: Koubura/angular-kahoot/tree/master/kahoot
          with:
            node-version: 12.x
            angular: 8.x